services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Zeroseven\Rampage\:
        resource: '../Classes/*'

    Zeroseven\Rampage\Command\DetectionCommand:
        tags:
            -   name: console.command
                command: 'rampage:detection'
                description: 'Detect objects and categories'
                hidden: false
                schedulable: true

    Zeroseven\Rampage\Registration\EventListener\ValidateRegistrationEvent:
        tags:
            - name: event.listener
              identifier: 'rampage/registration-validation'
              event: TYPO3\CMS\Core\Configuration\Event\AfterTcaCompilationEvent

    Zeroseven\Rampage\Registration\EventListener\AddTCAEvent:
        tags:
            - name: event.listener
              identifier: 'rampage/registration-add-tca'
              after: 'rampage/registration-validation'
              event: TYPO3\CMS\Core\Configuration\Event\AfterTcaCompilationEvent

    Zeroseven\Rampage\Registration\EventListener\CheckExtensionConfigurationEvent:
        tags:
            - name: event.listener
              identifier: 'rampage/registration-check-extension-configuration'
              event: Zeroseven\Rampage\Registration\Event\BeforeStoreRegistrationEvent

    Zeroseven\Rampage\Registration\EventListener\IconRegistryEvent:
        tags:
            - name: event.listener
              identifier: 'rampage/registration-icon-registry'
              event: Zeroseven\Rampage\Registration\Event\BeforeStoreRegistrationEvent

    Zeroseven\Rampage\Registration\EventListener\AddTSConfigEvent:
        tags:
            - name: event.listener
              identifier: 'rampage/registration-add-tsconfig'
              event: Zeroseven\Rampage\Registration\Event\AfterStoreRegistrationEvent

    Zeroseven\Rampage\Registration\EventListener\AddUserTSConfigEvent:
        tags:
            - name: event.listener
              identifier: 'rampage/registration-add-usertsconfig'
              event: Zeroseven\Rampage\Registration\Event\AfterStoreRegistrationEvent

    Zeroseven\Rampage\Registration\EventListener\AddTypoScriptEvent:
        tags:
            - name: event.listener
              identifier: 'rampage/registration-add-typoscript'
              event: Zeroseven\Rampage\Registration\Event\AfterStoreRegistrationEvent

    Zeroseven\Rampage\Registration\EventListener\RegisterPluginEvent:
        tags:
            - name: event.listener
              identifier: 'rampage/registration-plugin'
              event: Zeroseven\Rampage\Registration\Event\AfterStoreRegistrationEvent

    Zeroseven\Rampage\EventListener\DetectObjects:
        tags:
            - name: event.listener
              identifier: 'rampage/detect-registration'
              event: TYPO3\CMS\Backend\Controller\Event\BeforeFormEnginePageInitializedEvent

    Zeroseven\Rampage\EventListener\DisplayObjectRelations:
        tags:
            - name: event.listener
              identifier: 'rampage/display-object-relations'
              event: TYPO3\CMS\Backend\Controller\Event\BeforeFormEnginePageInitializedEvent

    Zeroseven\Rampage\EventListener\DisplayObjectInformation:
        tags:
            - name: event.listener
              identifier: 'rampage/display-object-affiliation'
              event: TYPO3\CMS\Backend\Controller\Event\BeforeFormEnginePageInitializedEvent
